from enum import Enum


class BillFieldLabel(str, Enum):
    trade_time = "交易时间"
    appid = "公众账号ID"
    mchid = "商户号"
    special_mchid = "特约商户号"
    device_id = "设备号"
    transaction_id = "微信订单号"
    out_trade_no = "商户订单号"
    openid = "用户标识"
    trade_type = "交易类型"
    trade_state = "交易状态"
    bank_type = "付款银行"
    currency = "货币种类"
    settlement_total = "应结订单金额"
    discount_amount = "代金券金额"
    refund_id = "微信退款单号"
    out_refund_no = "商户退款单号"
    refund_amount = "退款金额"
    promotion_refund_amount = "充值券退款金额"
    refund_type = "退款类型"
    refund_status = "退款状态"
    goods_name = "商品名称"
    merchant_data_package = "商户数据包"
    transaction_fee = "手续费"
    transaction_rate = "费率"
    bill_amount = "订单金额"
    requested_refund_amount = "申请退款金额"
    rate_remark = "费率备注"
