"""empty message

Revision ID: 1006e3c39ba5
Revises: b7531122536f
Create Date: 2021-10-06 15:19:05.534639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1006e3c39ba5'
down_revision = 'b7531122536f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8_client', sa.Column('company', sa.String(length=80), nullable=True))
    op.drop_column('ticket_laiu8_client', 'alias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8_client', sa.Column('alias', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True))
    op.drop_column('ticket_laiu8_client', 'company')
    # ### end Alembic commands ###
