"""empty message

Revision ID: 1a388fbc6779
Revises: 9fed86e4e78a
Create Date: 2021-11-05 00:54:52.383379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a388fbc6779'
down_revision = '9fed86e4e78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_group', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('company_group', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('cooperate_type', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('cooperate_type', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('map_cooperate_company', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('map_cooperate_company', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('permit_code', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('permit_code', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('role', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('role', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('route', sa.Column('permission', sa.String(length=80), nullable=True))
    op.add_column('route', sa.Column('status', sa.String(length=2), nullable=True))
    op.add_column('route', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('route', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.drop_index('name', table_name='route')
    op.create_index(op.f('ix_route_name'), 'route', ['name'], unique=True)
    op.add_column('route_meta', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('route_meta', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('route_tree', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('route_tree', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('subsidiary_company', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('subsidiary_company', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('utils_default_rsa', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('utils_default_rsa', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('utils_rsa', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('utils_rsa', sa.Column('update_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utils_rsa', 'update_time')
    op.drop_column('utils_rsa', 'create_time')
    op.drop_column('utils_default_rsa', 'update_time')
    op.drop_column('utils_default_rsa', 'create_time')
    op.drop_column('subsidiary_company', 'update_time')
    op.drop_column('subsidiary_company', 'create_time')
    op.drop_column('route_tree', 'update_time')
    op.drop_column('route_tree', 'create_time')
    op.drop_column('route_meta', 'update_time')
    op.drop_column('route_meta', 'create_time')
    op.drop_index(op.f('ix_route_name'), table_name='route')
    op.create_index('name', 'route', ['name'], unique=False)
    op.drop_column('route', 'update_time')
    op.drop_column('route', 'create_time')
    op.drop_column('route', 'status')
    op.drop_column('route', 'permission')
    op.drop_column('role', 'update_time')
    op.drop_column('role', 'create_time')
    op.drop_column('permit_code', 'update_time')
    op.drop_column('permit_code', 'create_time')
    op.drop_column('map_cooperate_company', 'update_time')
    op.drop_column('map_cooperate_company', 'create_time')
    op.drop_column('cooperate_type', 'update_time')
    op.drop_column('cooperate_type', 'create_time')
    op.drop_column('company_group', 'update_time')
    op.drop_column('company_group', 'create_time')
    # ### end Alembic commands ###
