"""empty message

Revision ID: 1d68ce4f3a3d
Revises: 1006e3c39ba5
Create Date: 2021-10-06 15:19:47.567803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d68ce4f3a3d'
down_revision = '1006e3c39ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8_client', sa.Column('company_name', sa.String(length=80), nullable=True))
    op.drop_column('ticket_laiu8_client', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8_client', sa.Column('company', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True))
    op.drop_column('ticket_laiu8_client', 'company_name')
    # ### end Alembic commands ###
