"""empty message

Revision ID: 261ce284e86b
Revises: d1cbbfa729fb
Create Date: 2021-10-07 15:32:50.412482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '261ce284e86b'
down_revision = 'd1cbbfa729fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8', sa.Column('line_name', sa.String(length=80), nullable=True, comment='航线名称=北海-涠洲/涠洲-北海/北海-海口...'))
    op.drop_column('ticket_laiu8', 'linename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8', sa.Column('linename', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True, comment='航线名称=北海-涠洲/涠洲-北海/北海-海口...'))
    op.drop_column('ticket_laiu8', 'line_name')
    # ### end Alembic commands ###
