"""empty message

Revision ID: 29e57466471b
Revises: ccc7df1df309
Create Date: 2021-11-10 21:44:10.136584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29e57466471b'
down_revision = 'ccc7df1df309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_aliyun', 'biz_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=False)
    op.alter_column('sms_aliyun', 'request_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=True)
    op.drop_index('request_id', table_name='sms_aliyun')
    op.create_unique_constraint(None, 'sms_aliyun', ['biz_id'])
    op.add_column('sms_aliyun_detail', sa.Column('biz_id', sa.String(length=80), nullable=True))
    op.drop_constraint('sms_aliyun_detail_ibfk_1', 'sms_aliyun_detail', type_='foreignkey')
    op.create_foreign_key(None, 'sms_aliyun_detail', 'sms_aliyun', ['biz_id'], ['biz_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_aliyun_detail', type_='foreignkey')
    op.create_foreign_key('sms_aliyun_detail_ibfk_1', 'sms_aliyun_detail', 'sms_aliyun', ['request_id'], ['request_id'])
    op.drop_column('sms_aliyun_detail', 'biz_id')
    op.drop_constraint(None, 'sms_aliyun', type_='unique')
    op.create_index('request_id', 'sms_aliyun', ['request_id'], unique=False)
    op.alter_column('sms_aliyun', 'request_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=False)
    op.alter_column('sms_aliyun', 'biz_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=True)
    # ### end Alembic commands ###
