"""empty message

Revision ID: 368fa1a22841
Revises: 88f856834979
Create Date: 2021-10-11 16:11:43.073033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '368fa1a22841'
down_revision = '88f856834979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auxiliary_account', sa.Column('name', sa.String(length=80), nullable=False))
    op.drop_column('auxiliary_account', 'title')
    op.add_column('finance_account', sa.Column('name', sa.String(length=80), nullable=True))
    op.drop_column('finance_account', 'caption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_account', sa.Column('caption', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True))
    op.drop_column('finance_account', 'name')
    op.add_column('auxiliary_account', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False))
    op.drop_column('auxiliary_account', 'name')
    # ### end Alembic commands ###
