"""empty message

Revision ID: 38e5dad9e314
Revises: 68ce4c0ddcba
Create Date: 2021-10-10 14:08:05.549777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e5dad9e314'
down_revision = '68ce4c0ddcba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auxiliary_account', sa.Column('detail_table_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auxiliary_account', 'detail_table_name')
    # ### end Alembic commands ###
