"""empty message

Revision ID: 47e7998fe2e5
Revises: c75a0a695a51
Create Date: 2021-10-10 15:16:09.306349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47e7998fe2e5'
down_revision = 'c75a0a695a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('account', sa.String(length=80), nullable=False))
    op.add_column('bank_account', sa.Column('account_name', sa.String(length=80), nullable=True))
    op.add_column('bank_account', sa.Column('bank_name', sa.String(length=80), nullable=True))
    op.add_column('bank_account', sa.Column('bank_address', sa.String(length=80), nullable=True))
    op.add_column('bank_account', sa.Column('create_date', sa.DATETIME(), nullable=True))
    op.create_unique_constraint(None, 'bank_account', ['account'])
    op.drop_column('bank_account', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True))
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.drop_column('bank_account', 'create_date')
    op.drop_column('bank_account', 'bank_address')
    op.drop_column('bank_account', 'bank_name')
    op.drop_column('bank_account', 'account_name')
    op.drop_column('bank_account', 'account')
    # ### end Alembic commands ###
