"""empty message

Revision ID: 483588f52d5c
Revises: 58796fd1ac15
Create Date: 2021-09-30 00:23:39.831550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483588f52d5c'
down_revision = '58796fd1ac15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_closure_table', sa.Column('distance', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_closure_table', 'distance')
    # ### end Alembic commands ###
