"""empty message

Revision ID: 4e19259e7b7e
Revises: 29e57466471b
Create Date: 2021-11-14 19:49:24.700294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e19259e7b7e'
down_revision = '29e57466471b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenpay_bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_time', sa.DATETIME(), nullable=True, comment='交易时间'),
    sa.Column('appid', sa.String(length=80), nullable=True, comment='公众账号ID'),
    sa.Column('mchid', sa.String(length=80), nullable=True, comment='商户号'),
    sa.Column('special_mchid', sa.String(length=80), nullable=True, comment='特约商户号'),
    sa.Column('device_id', sa.String(length=80), nullable=True, comment='设备号'),
    sa.Column('transaction_id', sa.String(length=80), nullable=True, comment='微信订单号'),
    sa.Column('out_trade_no', sa.String(length=80), nullable=True, comment='商户订单号'),
    sa.Column('openid', sa.String(length=80), nullable=True, comment='用户标识'),
    sa.Column('trade_type', sa.String(length=10), nullable=True, comment='交易类型'),
    sa.Column('trade_state', sa.String(length=10), nullable=True, comment='交易状态'),
    sa.Column('bank_type', sa.String(length=80), nullable=True, comment='付款银行'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='货币种类'),
    sa.Column('settlement_total', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='应结订单金额'),
    sa.Column('discount_amount', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='代金券金额'),
    sa.Column('refund_id', sa.String(length=80), nullable=True, comment='微信退款单号'),
    sa.Column('out_refund_no', sa.String(length=80), nullable=True, comment='商户退款单号'),
    sa.Column('refund_amount', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='退款金额'),
    sa.Column('promotion_refund_amount', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='充值券退款金额'),
    sa.Column('refund_type', sa.String(length=10), nullable=True, comment='退款类型'),
    sa.Column('refund_status', sa.String(length=10), nullable=True, comment='退款状态'),
    sa.Column('goods_name', sa.String(length=80), nullable=True, comment='商品名称'),
    sa.Column('merchant_data_package', sa.String(length=80), nullable=True, comment='商户数据包'),
    sa.Column('transaction_fee', sa.DECIMAL(precision=10, scale=5), nullable=True, comment='手续费'),
    sa.Column('transaction_rate', sa.String(length=80), nullable=True, comment='费率'),
    sa.Column('bill_amount', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='订单金额'),
    sa.Column('requested_refund_amount', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='申请退款金额'),
    sa.Column('rate_remark', sa.String(length=80), nullable=True, comment='费率备注'),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenpay_bill_bill_amount'), 'tenpay_bill', ['bill_amount'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_discount_amount'), 'tenpay_bill', ['discount_amount'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_out_trade_no'), 'tenpay_bill', ['out_trade_no'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_promotion_refund_amount'), 'tenpay_bill', ['promotion_refund_amount'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_refund_amount'), 'tenpay_bill', ['refund_amount'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_refund_id'), 'tenpay_bill', ['refund_id'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_requested_refund_amount'), 'tenpay_bill', ['requested_refund_amount'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_settlement_total'), 'tenpay_bill', ['settlement_total'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_trade_time'), 'tenpay_bill', ['trade_time'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_transaction_fee'), 'tenpay_bill', ['transaction_fee'], unique=False)
    op.create_index(op.f('ix_tenpay_bill_transaction_id'), 'tenpay_bill', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenpay_bill_transaction_id'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_transaction_fee'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_trade_time'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_settlement_total'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_requested_refund_amount'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_refund_id'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_refund_amount'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_promotion_refund_amount'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_out_trade_no'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_discount_amount'), table_name='tenpay_bill')
    op.drop_index(op.f('ix_tenpay_bill_bill_amount'), table_name='tenpay_bill')
    op.drop_table('tenpay_bill')
    # ### end Alembic commands ###
