"""empty message

Revision ID: 53c8a1e1acec
Revises: 56285dfafed3
Create Date: 2021-10-10 16:25:03.582554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c8a1e1acec'
down_revision = '56285dfafed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_template', sa.Column('company_code', sa.String(length=80), nullable=True))
    op.add_column('voucher_template', sa.Column('voucher_date', sa.Date(), nullable=True))
    op.add_column('voucher_template', sa.Column('business_date', sa.Date(), nullable=True))
    op.add_column('voucher_template', sa.Column('period', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_template', 'period')
    op.drop_column('voucher_template', 'business_date')
    op.drop_column('voucher_template', 'voucher_date')
    op.drop_column('voucher_template', 'company_code')
    # ### end Alembic commands ###
