"""empty message

Revision ID: 56285dfafed3
Revises: 34c0f5c7a19b
Create Date: 2021-10-10 15:56:51.530820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56285dfafed3'
down_revision = '34c0f5c7a19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('company_group', sa.Column('code', sa.String(length=20), nullable=True))
    op.drop_column('company_group', 'financial_code')
    op.add_column('cooperate_company', sa.Column('code', sa.String(length=10), nullable=True))
    op.drop_column('cooperate_company', 'financial_code')
    op.add_column('subsidiary_company', sa.Column('code', sa.String(length=10), nullable=True))
    op.drop_index('financial_code', table_name='subsidiary_company')
    op.create_unique_constraint(None, 'subsidiary_company', ['code'])
    op.drop_column('subsidiary_company', 'financial_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subsidiary_company', sa.Column('financial_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True))
    op.drop_constraint(None, 'subsidiary_company', type_='unique')
    op.create_index('financial_code', 'subsidiary_company', ['financial_code'], unique=False)
    op.drop_column('subsidiary_company', 'code')
    op.add_column('cooperate_company', sa.Column('financial_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True))
    op.drop_column('cooperate_company', 'code')
    op.add_column('company_group', sa.Column('financial_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=20), nullable=True))
    op.drop_column('company_group', 'code')
    op.drop_table('voucher_template')
    # ### end Alembic commands ###
