"""empty message

Revision ID: 58796fd1ac15
Revises: d009d20162df
Create Date: 2021-09-29 18:07:50.538796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58796fd1ac15'
down_revision = 'd009d20162df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_user2route_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route_tree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_tree_id'], ['route_tree.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_user2route_tree')
    # ### end Alembic commands ###
