"""empty message

Revision ID: 5d9bb3a88b21
Revises: ac9da92e1117
Create Date: 2021-10-10 21:43:56.771793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d9bb3a88b21'
down_revision = 'ac9da92e1117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookkeeping_template', sa.Column('auditor', sa.String(length=10), nullable=True))
    op.drop_column('bookkeeping_template', 'auditer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookkeeping_template', sa.Column('auditer', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True))
    op.drop_column('bookkeeping_template', 'auditor')
    # ### end Alembic commands ###
