"""empty message

Revision ID: 6901f068ddef
Revises: 92b1cb3ae054
Create Date: 2021-10-24 21:12:32.613730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6901f068ddef'
down_revision = '92b1cb3ae054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_laiu8_refund', 'ticket_laiu8_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'ticket_laiu8_refund', 'ticket_laiu8', ['ticket_laiu8_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_laiu8_refund', type_='foreignkey')
    op.alter_column('ticket_laiu8_refund', 'ticket_laiu8_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
