"""empty message

Revision ID: 6cdac8bbb0bc
Revises: d3fac23c3488
Create Date: 2021-09-17 00:59:58.491003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cdac8bbb0bc'
down_revision = 'd3fac23c3488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('before_enter', sa.String(length=255), nullable=True))
    op.drop_column('route', 'beforeEnter')
    op.add_column('route_meta', sa.Column('order_no', sa.Integer(), nullable=True))
    op.drop_column('route_meta', 'orderNo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_meta', sa.Column('orderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('route_meta', 'order_no')
    op.add_column('route', sa.Column('beforeEnter', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=True))
    op.drop_column('route', 'before_enter')
    # ### end Alembic commands ###
