"""empty message

Revision ID: 781a2de26e22
Revises: bc67a883a839
Create Date: 2021-09-13 17:50:39.076019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781a2de26e22'
down_revision = 'bc67a883a839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_code', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('real_name', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'real_name')
    op.drop_column('user', 'user_code')
    # ### end Alembic commands ###
