"""empty message

Revision ID: 7b2f0ba4107e
Revises: 1a388fbc6779
Create Date: 2021-11-05 00:57:46.847660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2f0ba4107e'
down_revision = '1a388fbc6779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket2finance', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('ticket2finance', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.add_column('ticket_laiu8_client', sa.Column('create_time', sa.DATETIME(), nullable=True))
    op.add_column('ticket_laiu8_client', sa.Column('update_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_laiu8_client', 'update_time')
    op.drop_column('ticket_laiu8_client', 'create_time')
    op.drop_column('ticket2finance', 'update_time')
    op.drop_column('ticket2finance', 'create_time')
    # ### end Alembic commands ###
