"""empty message

Revision ID: 88f856834979
Revises: 5d9bb3a88b21
Create Date: 2021-10-10 23:18:28.106458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88f856834979'
down_revision = '5d9bb3a88b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookkeeping_template', sa.Column('currency_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookkeeping_template', 'currency_amount')
    # ### end Alembic commands ###
