"""empty message

Revision ID: 90f017a2eab1
Revises: 7b2f0ba4107e
Create Date: 2021-11-10 16:20:40.256739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f017a2eab1'
down_revision = '7b2f0ba4107e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_aliyun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_numbers', sa.Text(), nullable=False),
    sa.Column('sign_name', sa.String(length=80), nullable=False),
    sa.Column('template_code', sa.String(length=80), nullable=False),
    sa.Column('template_param', sa.String(length=80), nullable=False),
    sa.Column('send_date', sa.String(length=10), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=False),
    sa.Column('biz_id', sa.String(length=80), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('message', sa.String(length=80), nullable=True),
    sa.Column('total_count', sa.String(length=10), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('sms_aliyun_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('err_code', sa.String(length=80), nullable=True),
    sa.Column('template_code', sa.String(length=80), nullable=True),
    sa.Column('out_id', sa.String(length=80), nullable=True),
    sa.Column('receive_date', sa.DateTime(), nullable=True),
    sa.Column('send_date', sa.DateTime(), nullable=True),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('send_status', sa.String(length=10), nullable=True, comment='1=等待回执,2=发送失败,3=发送成功'),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['sms_aliyun.request_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_aliyun_detail')
    op.drop_table('sms_aliyun')
    # ### end Alembic commands ###
