"""empty message

Revision ID: 92a9cbd4ea19
Revises: c30fb930f0db
Create Date: 2021-10-06 11:17:20.570486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a9cbd4ea19'
down_revision = 'c30fb930f0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_laiu8_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=20), nullable=True),
    sa.Column('uniform_social_credit_code', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cooperate_company', sa.Column('update_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cooperate_company', 'user', ['update_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cooperate_company', type_='foreignkey')
    op.drop_column('cooperate_company', 'update_user_id')
    op.drop_table('ticket_laiu8_client')
    # ### end Alembic commands ###
