"""empty message

Revision ID: 92b1cb3ae054
Revises: ada68f3d9b9f
Create Date: 2021-10-20 23:59:28.221138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b1cb3ae054'
down_revision = 'ada68f3d9b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket2finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True, comment='支付方式=现金/POS机/微信/支付宝/来游吧OTA预存款/转账'),
    sa.Column('user_type', sa.String(length=80), nullable=True, comment='用户类型=OTA/VIP/窗口/散客'),
    sa.Column('user_name', sa.String(length=80), nullable=True, comment='用户名称/下单人名称'),
    sa.Column('product_type', sa.String(length=80), nullable=True, comment='产品类型'),
    sa.Column('ticket_price', sa.Float(), nullable=True, comment='实际票价=原价-票价折扣'),
    sa.Column('get_voucher', sa.Float(), nullable=True, comment='产生的积分'),
    sa.Column('use_voucher', sa.Float(), nullable=True, comment='使用的积分'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket2finance')
    # ### end Alembic commands ###
