"""empty message

Revision ID: 9dcca05a8fce
Revises: ce2e240bd05e
Create Date: 2021-09-28 20:07:20.694809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcca05a8fce'
down_revision = 'ce2e240bd05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_meta', sa.Column('hide_menu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_meta', 'hide_menu')
    # ### end Alembic commands ###
