"""empty message

Revision ID: 9fed86e4e78a
Revises: d40c42324edd
Create Date: 2021-11-04 22:04:41.335733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fed86e4e78a'
down_revision = 'd40c42324edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=False)
    # ### end Alembic commands ###
