"""empty message

Revision ID: ac9da92e1117
Revises: c8d1521a545a
Create Date: 2021-10-10 18:41:35.264996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac9da92e1117'
down_revision = 'c8d1521a545a'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auxiliary_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('map_auxiliary_group2auxiliary_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auxiliary_group_id', sa.Integer(), nullable=True),
    sa.Column('auxiliary_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auxiliary_account_id'], ['auxiliary_account.id'], ),
    sa.ForeignKeyConstraint(['auxiliary_group_id'], ['auxiliary_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookkeeping_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('company_code', sa.String(length=80), nullable=True),
    sa.Column('bookkeeping_date', sa.Date(), nullable=True),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('period', sa.String(length=2), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('voucher_id', sa.String(length=80), nullable=True),
    sa.Column('entry_no', sa.String(length=10), nullable=True),
    sa.Column('abstract', sa.String(length=80), nullable=True),
    sa.Column('currency_type', sa.String(length=10), nullable=True),
    sa.Column('currency_rate', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=1), nullable=True, comment='1=debit;0=credit'),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('debit_finance_account_code', sa.String(length=80), nullable=True),
    sa.Column('debit_amount', sa.Float(), nullable=True),
    sa.Column('credit_finance_account_code', sa.String(length=80), nullable=True),
    sa.Column('credit_amount', sa.Float(), nullable=True),
    sa.Column('lister', sa.String(length=10), nullable=True),
    sa.Column('auditer', sa.String(length=10), nullable=True),
    sa.Column('confirmor', sa.String(length=10), nullable=True),
    sa.Column('attach_count', sa.Integer(), nullable=True),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('machine_module', sa.String(length=80), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('voucher_no', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('reference_information', sa.String(length=80), nullable=True),
    sa.Column('is_cashflow', sa.Boolean(), nullable=True),
    sa.Column('cashflow_tag', sa.String(length=10), nullable=True),
    sa.Column('business_no', sa.String(length=80), nullable=True),
    sa.Column('payment', sa.String(length=10), nullable=True),
    sa.Column('pay_no', sa.String(length=80), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credit_finance_account_code'], ['finance_account.code'], ),
    sa.ForeignKeyConstraint(['debit_finance_account_code'], ['finance_account.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.drop_table('voucher_template')
    op.drop_table('map_finance_account2auxiliary_account')
    op.add_column('finance_account', sa.Column('auxiliary_group_code', sa.String(length=80), nullable=True))
    op.alter_column('finance_account', 'direction',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=1),
               comment='1=debit;0=credit',
               existing_comment='1=credit;0=debit',
               existing_nullable=True)
    op.create_foreign_key(None, 'finance_account', 'auxiliary_group', ['auxiliary_group_code'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'finance_account', type_='foreignkey')
    op.alter_column('finance_account', 'direction',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=1),
               comment='1=credit;0=debit',
               existing_comment='1=debit;0=credit',
               existing_nullable=True)
    op.drop_column('finance_account', 'auxiliary_group_code')
    op.create_table('map_finance_account2auxiliary_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('finance_account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auxiliary_account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['auxiliary_account_id'], ['auxiliary_account.id'], name='map_finance_account2auxiliary_account_ibfk_1'),
    sa.ForeignKeyConstraint(['finance_account_id'], ['finance_account.id'], name='map_finance_account2auxiliary_account_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('voucher_template',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('company_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('voucher_date', sa.DATE(), nullable=True),
    sa.Column('business_date', sa.DATE(), nullable=True),
    sa.Column('period', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('bookkeeping_template')
    op.drop_table('map_auxiliary_group2auxiliary_account')
    op.drop_table('auxiliary_group')
    # ### end Alembic commands ###
