"""empty message

Revision ID: ada68f3d9b9f
Revises: 368fa1a22841
Create Date: 2021-10-12 00:18:18.216313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ada68f3d9b9f'
down_revision = '368fa1a22841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finance_account_tree')
    op.drop_table('map_auxiliary_group2auxiliary_account')
    op.drop_table('finance_account_closure_table')
    op.drop_index('code', table_name='ship_line')
    op.drop_table('ship_line')
    op.drop_index('code', table_name='ticket_seller')
    op.drop_table('ticket_seller')
    op.drop_index('code', table_name='department')
    op.drop_table('department')
    op.drop_index('account', table_name='bank_account')
    op.drop_index('code', table_name='bank_account')
    op.drop_table('bank_account')
    op.drop_index('code', table_name='bookkeeping_template')
    op.drop_table('bookkeeping_template')
    op.drop_index('code', table_name='employee')
    op.drop_table('employee')
    op.drop_index('code', table_name='auxiliary_account')
    op.drop_table('auxiliary_account')
    op.drop_index('code', table_name='finance_account')
    op.drop_table('finance_account')
    op.drop_index('code', table_name='payment_type')
    op.drop_table('payment_type')
    op.drop_index('code', table_name='ship')
    op.drop_table('ship')
    op.drop_index('code', table_name='auxiliary_group')
    op.drop_table('auxiliary_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auxiliary_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'auxiliary_group', ['code'], unique=False)
    op.create_table('ship',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'ship', ['code'], unique=False)
    op.create_table('payment_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'payment_type', ['code'], unique=False)
    op.create_table('finance_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('direction', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=1), nullable=True, comment='1=debit;0=credit'),
    sa.Column('auxiliary_group_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.ForeignKeyConstraint(['auxiliary_group_code'], ['auxiliary_group.code'], name='finance_account_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'finance_account', ['code'], unique=False)
    op.create_table('auxiliary_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('detail_table_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'auxiliary_account', ['code'], unique=False)
    op.create_table('employee',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'employee', ['code'], unique=False)
    op.create_table('bookkeeping_template',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('company_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('bookkeeping_date', sa.DATE(), nullable=True),
    sa.Column('business_date', sa.DATE(), nullable=True),
    sa.Column('period', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=2), nullable=True),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('voucher_id', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('entry_no', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('abstract', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('currency_type', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('currency_rate', mysql.FLOAT(), nullable=True),
    sa.Column('direction', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=1), nullable=True, comment='1=debit;0=credit'),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit_price', mysql.FLOAT(), nullable=True),
    sa.Column('debit_finance_account_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('debit_amount', mysql.FLOAT(), nullable=True),
    sa.Column('credit_finance_account_code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('credit_amount', mysql.FLOAT(), nullable=True),
    sa.Column('lister', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('confirmor', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('attach_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_confirm', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('machine_module', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('voucher_no', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('reference_information', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('is_cashflow', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cashflow_tag', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('business_no', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('payment', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('pay_no', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('auditor', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=10), nullable=True),
    sa.Column('currency_amount', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['credit_finance_account_code'], ['finance_account.code'], name='bookkeeping_template_ibfk_1'),
    sa.ForeignKeyConstraint(['debit_finance_account_code'], ['finance_account.code'], name='bookkeeping_template_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'bookkeeping_template', ['code'], unique=False)
    op.create_table('bank_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('account', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('account_name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('bank_branch_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('bank_address', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('cancel_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'bank_account', ['code'], unique=False)
    op.create_index('account', 'bank_account', ['account'], unique=False)
    op.create_table('department',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'department', ['code'], unique=False)
    op.create_table('ticket_seller',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'ticket_seller', ['code'], unique=False)
    op.create_table('ship_line',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'ship_line', ['code'], unique=False)
    op.create_table('finance_account_closure_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tree_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ancestor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('descendant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('distance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('depth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['finance_account.id'], name='finance_account_closure_table_ibfk_1'),
    sa.ForeignKeyConstraint(['descendant_id'], ['finance_account.id'], name='finance_account_closure_table_ibfk_2'),
    sa.ForeignKeyConstraint(['tree_id'], ['finance_account_tree.id'], name='finance_account_closure_table_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('map_auxiliary_group2auxiliary_account',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('auxiliary_group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auxiliary_account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['auxiliary_account_id'], ['auxiliary_account.id'], name='map_auxiliary_group2auxiliary_account_ibfk_1'),
    sa.ForeignKeyConstraint(['auxiliary_group_id'], ['auxiliary_group.id'], name='map_auxiliary_group2auxiliary_account_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('finance_account_tree',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
