"""empty message

Revision ID: b7531122536f
Revises: 92a9cbd4ea19
Create Date: 2021-10-06 12:08:50.042157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7531122536f'
down_revision = '92a9cbd4ea19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_laiu8_client', sa.Column('cooperate_start_time', sa.DATETIME(), nullable=True))
    op.add_column('ticket_laiu8_client', sa.Column('cooperate_end_time', sa.DATETIME(), nullable=True))
    op.add_column('ticket_laiu8_client', sa.Column('manager', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_laiu8_client', 'manager')
    op.drop_column('ticket_laiu8_client', 'cooperate_end_time')
    op.drop_column('ticket_laiu8_client', 'cooperate_start_time')
    # ### end Alembic commands ###
