"""empty message

Revision ID: bc67a883a839
Revises: 
Create Date: 2021-09-07 15:58:01.849869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc67a883a839'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_name_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniform_social_credit_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('begin_time', sa.DATETIME(), nullable=True),
    sa.Column('end_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperate_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subsidiary_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniform_social_credit_code', sa.String(length=20), nullable=True),
    sa.Column('financial_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cooperate_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniform_social_credit_code', sa.String(length=20), nullable=True),
    sa.Column('financial_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('create_user_id', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('confirm_time', sa.DATETIME(), nullable=True),
    sa.Column('confirm_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=2), server_default='1', nullable=True, comment='1=onsave;2=submitted;3=verified;4=to be modified;5=modified;6=abandon;'),
    sa.ForeignKeyConstraint(['confirm_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['create_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_user2company_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_group_id'], ['company_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_user2subsidiary_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subsidiary_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subsidiary_company_id'], ['subsidiary_company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('utils_rsa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('map_cooperate_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subsidiary_company_id', sa.Integer(), nullable=True),
    sa.Column('cooperate_company_id', sa.Integer(), nullable=True),
    sa.Column('cooperate_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cooperate_company_id'], ['cooperate_company.id'], ),
    sa.ForeignKeyConstraint(['cooperate_type_id'], ['cooperate_type.id'], ),
    sa.ForeignKeyConstraint(['subsidiary_company_id'], ['subsidiary_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_cooperate_company')
    op.drop_table('utils_rsa')
    op.drop_table('token_blocklist')
    op.drop_table('map_user2subsidiary_company')
    op.drop_table('map_user2company_group')
    op.drop_table('cooperate_company')
    op.drop_table('user')
    op.drop_table('subsidiary_company')
    op.drop_table('cooperate_type')
    op.drop_table('company_name_history')
    op.drop_table('company_group')
    # ### end Alembic commands ###
