"""empty message

Revision ID: c30fb930f0db
Revises: 23b96ae47308
Create Date: 2021-10-05 17:21:58.770855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30fb930f0db'
down_revision = '23b96ae47308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_group', sa.Column('color', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_group', 'color')
    # ### end Alembic commands ###
