"""empty message

Revision ID: c8d1521a545a
Revises: 53c8a1e1acec
Create Date: 2021-10-10 16:38:31.808772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8d1521a545a'
down_revision = '53c8a1e1acec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_laiu8', 'full_ticket_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='原价',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'discount_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'ticket_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='实际票价=原价-票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'get_voucher',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='产生的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'use_voucher',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='使用的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'real_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='实际支付价格=实际票价-使用的积分=<微信订单金额>/<支付宝收入金额>',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_client', 'sales',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('ticket_laiu8_refund', 'fee',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='手续费',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_refund', 'refund_amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_comment='退款金额',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_laiu8_refund', 'refund_amount',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='退款金额',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_refund', 'fee',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='手续费',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_client', 'sales',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'real_price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='实际支付价格=实际票价-使用的积分=<微信订单金额>/<支付宝收入金额>',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'use_voucher',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='使用的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'get_voucher',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='产生的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'ticket_price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='实际票价=原价-票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'discount_price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'full_ticket_price',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_comment='原价',
               existing_nullable=True)
    # ### end Alembic commands ###
