"""empty message

Revision ID: cb035a497b2f
Revises: f7c8fd36558c
Create Date: 2021-09-26 22:18:00.888837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb035a497b2f'
down_revision = 'f7c8fd36558c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utils_default_rsa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utils_default_rsa')
    # ### end Alembic commands ###
