"""empty message

Revision ID: ccc7df1df309
Revises: 90f017a2eab1
Create Date: 2021-11-10 18:30:18.174813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccc7df1df309'
down_revision = '90f017a2eab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_aliyun', 'template_param',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_aliyun', 'template_param',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
