"""empty message

Revision ID: d009d20162df
Revises: 9dcca05a8fce
Create Date: 2021-09-29 15:31:54.189216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd009d20162df'
down_revision = '9dcca05a8fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('route_closure_table', sa.Column('tree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'route_closure_table', 'route_tree', ['tree_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_closure_table', type_='foreignkey')
    op.drop_column('route_closure_table', 'tree_id')
    op.drop_table('route_tree')
    # ### end Alembic commands ###
