"""empty message

Revision ID: d31e555b4341
Revises: 6901f068ddef
Create Date: 2021-10-24 21:21:59.643919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31e555b4341'
down_revision = '6901f068ddef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ticket_laiu8_cabin_name'), 'ticket_laiu8', ['cabin_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_change_time'), 'ticket_laiu8', ['change_time'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_change_type'), 'ticket_laiu8', ['change_type'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_change_user_name'), 'ticket_laiu8', ['change_user_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_channel_name'), 'ticket_laiu8', ['channel_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_create_time'), 'ticket_laiu8', ['create_time'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_departure_datetime'), 'ticket_laiu8', ['departure_datetime'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_discount_price'), 'ticket_laiu8', ['discount_price'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_full_ticket_price'), 'ticket_laiu8', ['full_ticket_price'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_get_voucher'), 'ticket_laiu8', ['get_voucher'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_id'), 'ticket_laiu8', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_is_lock'), 'ticket_laiu8', ['is_lock'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_line_name'), 'ticket_laiu8', ['line_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_mobile'), 'ticket_laiu8', ['mobile'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_order_id'), 'ticket_laiu8', ['order_id'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_order_no'), 'ticket_laiu8', ['order_no'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_passenger_id_no'), 'ticket_laiu8', ['passenger_id_no'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_passenger_name'), 'ticket_laiu8', ['passenger_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_pay_id'), 'ticket_laiu8', ['pay_id'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_payment_method'), 'ticket_laiu8', ['payment_method'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_payment_time'), 'ticket_laiu8', ['payment_time'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_product_type'), 'ticket_laiu8', ['product_type'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_real_price'), 'ticket_laiu8', ['real_price'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_seat_memo'), 'ticket_laiu8', ['seat_memo'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ship_name'), 'ticket_laiu8', ['ship_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ticket_change_channel_name'), 'ticket_laiu8', ['ticket_change_channel_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ticket_no'), 'ticket_laiu8', ['ticket_no'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ticket_no_new'), 'ticket_laiu8', ['ticket_no_new'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ticket_price'), 'ticket_laiu8', ['ticket_price'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ticket_status'), 'ticket_laiu8', ['ticket_status'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_ticket_type_name'), 'ticket_laiu8', ['ticket_type_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_use_voucher'), 'ticket_laiu8', ['use_voucher'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_user_id'), 'ticket_laiu8', ['user_id'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_user_name'), 'ticket_laiu8', ['user_name'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_user_type'), 'ticket_laiu8', ['user_type'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_refund_fee'), 'ticket_laiu8_refund', ['fee'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_refund_refund_amount'), 'ticket_laiu8_refund', ['refund_amount'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_refund_refund_id'), 'ticket_laiu8_refund', ['refund_id'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_refund_ticket_no'), 'ticket_laiu8_refund', ['ticket_no'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_refund_ticket_refund_finish_time'), 'ticket_laiu8_refund', ['ticket_refund_finish_time'], unique=False)
    op.create_index(op.f('ix_ticket_laiu8_refund_ticket_refund_method'), 'ticket_laiu8_refund', ['ticket_refund_method'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_laiu8_refund_ticket_refund_method'), table_name='ticket_laiu8_refund')
    op.drop_index(op.f('ix_ticket_laiu8_refund_ticket_refund_finish_time'), table_name='ticket_laiu8_refund')
    op.drop_index(op.f('ix_ticket_laiu8_refund_ticket_no'), table_name='ticket_laiu8_refund')
    op.drop_index(op.f('ix_ticket_laiu8_refund_refund_id'), table_name='ticket_laiu8_refund')
    op.drop_index(op.f('ix_ticket_laiu8_refund_refund_amount'), table_name='ticket_laiu8_refund')
    op.drop_index(op.f('ix_ticket_laiu8_refund_fee'), table_name='ticket_laiu8_refund')
    op.drop_index(op.f('ix_ticket_laiu8_user_type'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_user_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_user_id'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_use_voucher'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ticket_type_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ticket_status'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ticket_price'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ticket_no_new'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ticket_no'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ticket_change_channel_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_ship_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_seat_memo'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_real_price'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_product_type'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_payment_time'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_payment_method'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_pay_id'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_passenger_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_passenger_id_no'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_order_no'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_order_id'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_mobile'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_line_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_is_lock'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_id'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_get_voucher'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_full_ticket_price'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_discount_price'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_departure_datetime'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_create_time'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_channel_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_change_user_name'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_change_type'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_change_time'), table_name='ticket_laiu8')
    op.drop_index(op.f('ix_ticket_laiu8_cabin_name'), table_name='ticket_laiu8')
    # ### end Alembic commands ###
