"""empty message

Revision ID: d3fac23c3488
Revises: 81506df2ac04
Create Date: 2021-09-17 00:58:31.595761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fac23c3488'
down_revision = '81506df2ac04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('ignore_auth', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.String(length=80), nullable=True),
    sa.Column('ignore_keep_alive', sa.Boolean(), nullable=True),
    sa.Column('affix', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=80), nullable=True),
    sa.Column('frame_src', sa.String(length=255), nullable=True),
    sa.Column('transition_name', sa.String(length=80), nullable=True),
    sa.Column('hide_breadcrumb', sa.Boolean(), nullable=True),
    sa.Column('carry_param', sa.Boolean(), nullable=True),
    sa.Column('hide_children_in_menu', sa.Boolean(), nullable=True),
    sa.Column('current_active_menu', sa.String(length=255), nullable=True),
    sa.Column('hide_tab', sa.Boolean(), nullable=True),
    sa.Column('orderNo', sa.Integer(), nullable=True),
    sa.Column('ignore_route', sa.Boolean(), nullable=True),
    sa.Column('hide_path_for_children', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('alias', sa.String(length=80), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('redirect', sa.String(length=255), nullable=True),
    sa.Column('beforeEnter', sa.String(length=255), nullable=True),
    sa.Column('props', sa.String(length=255), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['route_meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    op.drop_table('route_meta')
    # ### end Alembic commands ###
