"""empty message

Revision ID: d40c42324edd
Revises: d31e555b4341
Create Date: 2021-10-28 15:57:16.387308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd40c42324edd'
down_revision = 'd31e555b4341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket2finance', 'ticket_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='实际票价=原价-票价折扣',
               existing_nullable=True)
    op.alter_column('ticket2finance', 'get_voucher',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='产生的积分',
               existing_nullable=True)
    op.alter_column('ticket2finance', 'use_voucher',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='使用的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'full_ticket_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='原价',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'discount_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'ticket_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='实际票价=原价-票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'get_voucher',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='产生的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'use_voucher',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='使用的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'real_price',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='实际支付价格=实际票价-使用的积分=<微信订单金额>/<支付宝收入金额>',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_client', 'sales',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_nullable=True)
    op.alter_column('ticket_laiu8_refund', 'fee',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='手续费',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_refund', 'refund_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(precision=10, scale=3),
               existing_comment='退款金额',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_laiu8_refund', 'refund_amount',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='退款金额',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_refund', 'fee',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='手续费',
               existing_nullable=True)
    op.alter_column('ticket_laiu8_client', 'sales',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'real_price',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='实际支付价格=实际票价-使用的积分=<微信订单金额>/<支付宝收入金额>',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'use_voucher',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='使用的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'get_voucher',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='产生的积分',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'ticket_price',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='实际票价=原价-票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'discount_price',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='票价折扣',
               existing_nullable=True)
    op.alter_column('ticket_laiu8', 'full_ticket_price',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='原价',
               existing_nullable=True)
    op.alter_column('ticket2finance', 'use_voucher',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='使用的积分',
               existing_nullable=True)
    op.alter_column('ticket2finance', 'get_voucher',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='产生的积分',
               existing_nullable=True)
    op.alter_column('ticket2finance', 'ticket_price',
               existing_type=sa.DECIMAL(precision=10, scale=3),
               type_=mysql.FLOAT(),
               existing_comment='实际票价=原价-票价折扣',
               existing_nullable=True)
    # ### end Alembic commands ###
