"""empty message

Revision ID: e580ac41c9b3
Revises: 7bd3ee7a5109
Create Date: 2021-10-05 15:36:20.246308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e580ac41c9b3'
down_revision = '7bd3ee7a5109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_company_group2subsidiary_company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_group_id', sa.Integer(), nullable=True),
    sa.Column('subsidiary_company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_group_id'], ['company_group.id'], ),
    sa.ForeignKeyConstraint(['subsidiary_company_id'], ['subsidiary_company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_company_group2subsidiary_company')
    # ### end Alembic commands ###
