"""empty message

Revision ID: ed2299374398
Revises: 2aaeb4f2cd14
Create Date: 2021-09-26 15:28:23.352825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed2299374398'
down_revision = '2aaeb4f2cd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('update_time', sa.DATETIME(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['mobile'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=80),
               nullable=False)
    op.drop_column('user', 'update_time')
    op.drop_column('user', 'mobile')
    # ### end Alembic commands ###
