"""empty message

Revision ID: fb48aaae1109
Revises: 47e7998fe2e5
Create Date: 2021-10-10 15:19:19.397089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb48aaae1109'
down_revision = '47e7998fe2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('cancel_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_account', 'cancel_date')
    # ### end Alembic commands ###
